### ISSUE TITLE
Adequately Rewarding Telos Contributors

### ISSUE THREAD

**Issue by z-meta** [Telos-Foundation/tips#20]
TIP:  0024
 Title:  Adequately Rewarding Telos Contributors
 Authors: Michael Gucci, MD; Z-Meta <email: Michael.Gucci@gmail.com>
 Status: Draft 
 Type:  Informational 
 Created: 2018-10-17

Title: Adequately rewarding Telos Contributors.

Abstract:

We propose to increase the Telos Founder’s Reward Pool from 6 Million TLOS to 12 Million TLOS: 
to account for the increased launch group participants since inception to receive a split of 6M TLOS and an unexpected extended launch period, 
to reflect the current bear market conditions and, 
to adequately compensate the work done by all the good people for their work in launching the Telos Network. 

Motivation:

The original proposal called for 6 million TLOS shared amongst 6 BPs. We have since changed this to reflect community feedback and have opened up the 6 million TLOS reward pool to all participants of the network. As a result, we have on-boarded over 100+ contributors to the Telos Launch Group. However, the unintended consequence of this openness is a much lower reward compensation to each contributor in a bear market.

Additionally, the expected launch of the Telos Blockchain Network was in the August – September timeframe, which has since been delayed by No-Go votes in September and October 2018.

We believe an increase of 12 million will provide adequate compensation to reflect the increase in launch participants as well as the extended delay in launching the network. 

We are very close to launching the Telos Network and this would not have been possible without the hard work done by all the good people involved in this project. Market conditions have changed since writing the White Paper and we are currently in a bear market. The opening price of TLOS is expected to be low and this may not adequately compensate all the hard work done by all these exceptional people. 

Rationale:

With the current bear market conditions, the expected opening price of TLOS is around $0.50 USD. Increasing the Telos Founder’s Rewards Pool to 12 Million TLOS will compensate for the depressed market conditions and adequately reward the hard work done by all the unexpectedly large number of exceptional launch participants involved with the Telos Project. 

Specification:
The increased token supply will come from additional issuance at launch.

Discussion:  (Discussion is open)

Copyright: This document is in the public domain

**Comment by robrigo** [comment]
This  has been merged into the repo. Thanks Michael. https://github.com/Telos-Foundation/tips/commit/dd5ac04dea3b57e2a4245b14a2c08a6826202b9c
