### ISSUE TITLE
TIP proposal re Ethereum Airdrop

### ISSUE THREAD

**Issue by TallJanSmit** [Telos-Foundation/tips#3]
Does this qualify as a TIP?
Best
Jan

Title: Ethereum airdrop
Authors: Jan Smit <jan@keten.io>
Status: Draft
Type: Informational
Created: 2018-08-02

Abstract
This proposal outlines a plan to boost Telos adoption by performing an airdrop of locked (non-transferable) ERC20s on all Ether accounts which can be converted to (for example) 10 Telos. The total converted amount can be capped at for example 10 Mln EOS on a first come first serve basis.

Motivation
Increase Telos adoption.

Rationale
As Ethereum has the most similar use case to EOSIO chains this airdrop seeks to familiarize Ethereum owners with Telos.

Specification
Perform an airdrop of locked (non-transferable) ERC20s on all Ether accounts which can be exchanged for (for example) 10 Telos. The mechanism through which to exchange the ERC-20 to Telos tokens needs to be further detailed. Ideally the conversion takes place through the Telos Foundation website so people understand who the benefactor is.

Optional proposal A:
Airdrop on Ethereum

Optional proposal B:
Airdrop on EOS accounts created after Genesis

Questions
Ethereum airdrop costs to be researched

**Comment by robrigo** [comment]
Good start. Please use TIP-0006 for numbering!

**Comment by DouglasHorn** [comment]
Yes, there is a format for TIPs. Please put this in and format it as Rob mentions. I think this is worth discussing.
